###########################################################################
# 
#  Copyright 2019 Google Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
###########################################################################

"""This is a technical settings file that needs to be extended with additional settings.

To launch the StarThinker UI or use manage.py please specify --settings=ui.settings_open

 - See: starthinker.ui.ui.settings_*.py
 - For example: python manage.py runserver localhost:8000 --settings=ui.settings_open

### Django Specific Documentation:
  - Generated by 'django-admin startproject' using Django 1.11.1.
  - For more information on this file, see: https://docs.djangoproject.com/en/1.11/topics/settings/
  - For the full list of settings and their values, see: https://docs.djangoproject.com/en/1.11/ref/settings/
  - For production, see: https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

"""

import os

# General StarThinker constants that can also be used from the command line interface
from starthinker.config import UI_PROJECT, UI_CLIENT, UI_SERVICE, UI_TOPIC, UI_CRON

# To reduce accidental production as debug afer code pull, a blank file is used to check for mode ( the server always has it )
DEVELOPMENT_MODE = not os.path.isfile('/mnt/SERVER')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = DEVELOPMENT_MODE

ADMIN_ENABLED = False

INSTALLED_APPS = [
  'django.contrib.admin',
  'django.contrib.auth',
  'django.contrib.contenttypes',
  'django.contrib.sessions',
  'django.contrib.messages',
  'django.contrib.staticfiles',
  'starthinker.ui.account',
  'starthinker.ui.recipe',
  'starthinker.ui.storage',
  'starthinker.ui.project',
  'starthinker.ui.website',
]

MIDDLEWARE = [
  'django.middleware.security.SecurityMiddleware',
  'django.contrib.sessions.middleware.SessionMiddleware',
  'django.middleware.common.CommonMiddleware',
  'django.middleware.csrf.CsrfViewMiddleware',
  'django.contrib.auth.middleware.AuthenticationMiddleware',
  'django.contrib.messages.middleware.MessageMiddleware',
  'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Relative to current application load
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

TEMPLATES = [
  {
    'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'DIRS': [BASE_DIR + '/templates/',],
    'APP_DIRS': True,
    'OPTIONS': {
      'context_processors': [
        'django.template.context_processors.debug',
        'django.template.context_processors.request',
        'django.contrib.auth.context_processors.auth',
        'django.contrib.messages.context_processors.messages',
      ],
    },
  },
]

AUTH_PASSWORD_VALIDATORS = [
  { 'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', },
  { 'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', },
  { 'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', },
  { 'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', },
]

AUTHENTICATION_BACKENDS = [
  'django.contrib.auth.backends.ModelBackend',
]

USE_I18N = True
USE_L10N = True
USE_TZ = False

# User
AUTH_USER_MODEL = 'account.Account'

# Application Handler Map
ROOT_URLCONF = 'starthinker.ui.ui.urls'
