###########################################################################
#
#  Copyright 2017 Google Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
###########################################################################

Impression_Schema = [
  { "name":"Event Time", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"User ID", "type":"STRING", "mode":"NULLABLE" },
  { "name":"Advertiser ID", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"Campaign ID", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"Ad ID", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"Rendering ID", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"Creative Version", "type":"STRING", "mode":"NULLABLE" },
  { "name":"Site ID (DCM)", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"Country Code", "type":"STRING", "mode":"NULLABLE" },
  { "name":"State/Region", "type":"STRING", "mode":"NULLABLE" },
  { "name":"Browser/Platform ID", "type":"STRING", "mode":"NULLABLE" },
  { "name":"Browser/Platform Version", "type":"STRING", "mode":"NULLABLE" },
  { "name":"Designated Market Area (DMA) ID", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"City ID", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"ZIP/Postal Code", "type":"STRING", "mode":"NULLABLE" },
  { "name":"U Value", "type":"STRING", "mode":"NULLABLE" },
  { "name":"Event Type", "type":"STRING", "mode":"NULLABLE" },
  { "name":"Event Sub-Type", "type":"STRING", "mode":"NULLABLE" },
  { "name":"DBM Auction ID", "type":"STRING", "mode":"NULLABLE" },
  { "name":"DBM Request Time", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM Advertiser ID", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM Insertion Order ID", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM Line Item ID", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM Creative ID", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM Bid Price (USD)", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM Bid Price (Partner Currency)", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM Bid Price (Advertiser Currency)", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM URL", "type":"STRING", "mode":"NULLABLE" },
  { "name":"DBM Site ID", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM Language", "type":"STRING", "mode":"NULLABLE" },
  { "name":"DBM Adx Page Categories", "type":"STRING", "mode":"NULLABLE" },
  { "name":"DBM Matching Targeted Keywords", "type":"STRING", "mode":"NULLABLE" },
  { "name":"DBM Exchange ID", "type":"STRING", "mode":"NULLABLE" },
  { "name":"DBM Attributed Inventory Source External ID", "type":"STRING", "mode":"NULLABLE" },
  { "name":"DBM Attributed Inventory Source Is Public", "type":"STRING", "mode":"NULLABLE" },
  { "name":"DBM Ad Position", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM Country Code", "type":"STRING", "mode":"NULLABLE" },
  { "name":"DBM ZIP/Postal Code", "type":"STRING", "mode":"NULLABLE" },
  { "name":"DBM Browser/Platform ID", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM Net Speed", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM Matching Targeted Segments", "type":"STRING", "mode":"NULLABLE" },
  { "name":"DBM ISP ID", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM Device Type", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM Mobile Model ID", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"Placement ID", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"Operating System ID", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM Designated Market Area (DMA) ID", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM State/Region ID", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM City ID", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM Browser Timezone Offset Minutes", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM Operating System ID", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM Mobile Make ID", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"Partner 1 ID", "type":"STRING", "mode":"NULLABLE" },
  { "name":"Partner 2 ID", "type":"STRING", "mode":"NULLABLE" },
  { "name":"Partner 3 ID", "type":"STRING", "mode":"NULLABLE" },
  { "name":"Partner 4 ID", "type":"STRING", "mode":"NULLABLE" },
  { "name":"Partner 5 ID", "type":"STRING", "mode":"NULLABLE" },
  { "name":"Null User ID Reason Groups", "type":"STRING", "mode":"NULLABLE" },
  { "name":"City", "type":"STRING", "mode":"NULLABLE" },
  { "name":"Impression ID", "type":"STRING", "mode":"NULLABLE" },
  { "name":"Referrer URL", "type":"STRING", "mode":"NULLABLE" },
  { "name":"DBM Country ID", "type":"STRING", "mode":"NULLABLE" },
  { "name":"DBM View State", "type":"STRING", "mode":"NULLABLE" },
  { "name":"Creative Pixel Size", "type":"STRING", "mode":"NULLABLE" },
  { "name":"DBM Media Cost (USD)", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM Media Cost (Partner Currency)", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM Media Cost (Advertiser Currency)", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM Revenue (USD)", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM Revenue (Partner Currency)", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM Revenue (Advertiser Currency)", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM CPM Fee 1 (USD)", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM CPM Fee 1 (Partner Currency)", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM CPM Fee 1 (Advertiser Currency)", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM CPM Fee 2 (USD)", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM CPM Fee 2 (Partner Currency)", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM CPM Fee 2 (Advertiser Currency)", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM CPM Fee 3 (USD)", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM CPM Fee 3 (Partner Currency)", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM CPM Fee 3 (Advertiser Currency)", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM CPM Fee 4 (USD)", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM CPM Fee 4 (Partner Currency)", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM CPM Fee 4 (Advertiser Currency)", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM CPM Fee 5 (USD)", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM CPM Fee 5 (Partner Currency)", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM CPM Fee 5 (Advertiser Currency)", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM Media Fee 1 (USD)", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM Media Fee 1 (Partner Currency)", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM Media Fee 1 (Advertiser Currency)", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM Media Fee 2 (USD)", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM Media Fee 2 (Partner Currency)", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM Media Fee 2 (Advertiser Currency)", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM Media Fee 3 (USD)", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM Media Fee 3 (Partner Currency)", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM Media Fee 3 (Advertiser Currency)", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM Media Fee 4 (USD)", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM Media Fee 4 (Partner Currency)", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM Media Fee 4 (Advertiser Currency)", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM Media Fee 5 (USD)", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM Media Fee 5 (Partner Currency)", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM Media Fee 5 (Advertiser Currency)", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM Data Fees (USD)", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM Data Fees (Partner Currency)", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM Data Fees (Advertiser Currency)", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"Total Revenue", "type":"FLOAT", "mode":"NULLABLE" },
  { "name":"Active View: Eligible Impressions", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"Active View: Viewable Impressions", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM Billable Cost (USD)", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM Billable Cost (Partner Currency)", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM Billable Cost (Advertiser Currency)", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM Total Media Cost (Partner Currency)", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM Total Media Cost (Advertiser Currency)", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"DBM Total Media Cost (USD)", "type":"INTEGER", "mode":"NULLABLE" },
  { "name":"Active View: Measurable Impressions", "type":"INTEGER", "mode":"NULLABLE" }
]