###########################################################################
#
#  Copyright 2017 Google Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
###########################################################################

DT_Field_Lookup = {
  "advertiser":"STRING",
  "ad_type":"STRING",
  "creative_version":"INTEGER",
  "city_id":"INTEGER",
  "Rich Media Event ID":"INTEGER",
  "Active View: Viewable Impressions":"INTEGER",
  "City ID":"INTEGER",
  "ad_click_url":"STRING",
  "creative_size":"STRING",
  "creative_last_modified_date":"INTEGER",
  "campaign_end_date":"INTEGER",
  "DBM URL":"STRING",
  "DBM Line Item ID":"INTEGER",
  "DBM Total Media Cost (Advertiser Currency)":"INTEGER",
  "Partner 4 ID":"STRING",
  "DBM Media Fee 5 (Advertiser Currency)":"INTEGER",
  "Event Time":"INTEGER",
  "DBM Mobile Model ID":"INTEGER",
  "advertiser_group_id":"INTEGER",
  "floodlight_variable_name":"STRING",
  "region_full_name":"STRING",
  "User ID":"STRING",
  "DBM CPM Fee 2 (Advertiser Currency)":"INTEGER",
  "Event Timers":"FLOAT",
  "creative_field_name":"STRING",
  "Rendering ID":"INTEGER",
  "creative_group1_id":"INTEGER",
  "DBM Net Speed":"INTEGER",
  "advertiser_group":"STRING",
  "Event Sub-Type":"STRING",
  "activity_id":"INTEGER",
  "DBM Bid Price (Advertiser Currency)":"INTEGER",
  "account_id":"INTEGER",
  "DBM Adx Page Categories":"STRING",
  "floodlight_config_id":"INTEGER",
  "DBM Media Fee 2 (Partner Currency)":"INTEGER",
  "placement_cost_structure":"STRING",
  "advertiser_id":"INTEGER",
  "ORD Value":"STRING",
  "placement_end_date":"INTEGER",
  "Null User ID Reason Groups":"STRING",
  "landing_page_url_id":"INTEGER",
  "Partner 2 ID":"STRING",
  "creative_field_value":"STRING",
  "DBM Bid Price (Partner Currency)":"INTEGER",
  "creative_rotation_type_id":"INTEGER",
  "dma_region_id":"INTEGER",
  "DBM Creative ID":"INTEGER",
  "operating_system":"STRING",
  "Campaign ID":"INTEGER",
  "placement_strategy_id":"INTEGER",
  "DBM Attributed Inventory Source External ID":"STRING",
  "activity_group_id":"INTEGER",
  "paid_search_keyword_id":"INTEGER",
  "Advertiser ID":"INTEGER",
  "creative_type_id":"INTEGER",
  "DBM View State":"STRING",
  "DBM CPM Fee 1 (Partner Currency)":"INTEGER",
  "DBM CPM Fee 1 (Advertiser Currency)":"INTEGER",
  "Other Data":"STRING",
  "Custom Event Counters":"INTEGER",
  "campaign_id":"INTEGER",
  "package_roadblock_id":"INTEGER",
  "content_category_id":"INTEGER",
  "Partner 1 ID":"STRING",
  "DBM Bid Price (USD)":"INTEGER",
  "browser_platform":"STRING",
  "DBM Total Media Cost (Partner Currency)":"INTEGER",
  "DBM Country Code":"STRING",
  "paid_search_match_type":"STRING",
  "DBM CPM Fee 5 (Advertiser Currency)":"INTEGER",
  "DBM Attributed Inventory Source Is Public":"STRING",
  "DBM State/Region ID":"INTEGER",
  "Partner 5 ID":"STRING",
  "Activity Type":"INTEGER",
  "DBM Media Fee 2 (USD)":"INTEGER",
  "creative_id":"INTEGER",
  "DBM Language":"STRING",
  "Rich Media Event Type ID":"INTEGER",
  "creative":"STRING",
  "Event Counters":"INTEGER",
  "creative_field_value_id":"INTEGER",
  "DBM Ad Position":"INTEGER",
  "DBM Revenue (USD)":"INTEGER",
  "DBM Total Media Cost (USD)":"INTEGER",
  "campaign":"STRING",
  "ad_id":"INTEGER",
  "paid_search_ad_group_id":"INTEGER",
  "paid_search_bid_strategy":"STRING",
  "Impression ID":"STRING",
  "Custom Event Timers":"INTEGER",
  "ad_type_id":"INTEGER",
  "site_directory":"STRING",
  "DBM Matching Targeted Keywords":"STRING",
  "creative_end_date":"INTEGER",
  "TRAN Value":"STRING",
  "creative_field_number":"INTEGER",
  "Operating System ID":"INTEGER",
  "State/Region":"STRING",
  "DBM Billable Cost (USD)":"INTEGER",
  "region":"STRING",
  "DBM CPM Fee 4 (Advertiser Currency)":"INTEGER",
  "package_roadblock_type":"STRING",
  "DBM CPM Fee 3 (USD)":"INTEGER",
  "U Value":"STRING",
  "paid_search_bid_strategy_id":"INTEGER",
  "ZIP/Postal Code":"STRING",
  "DBM Browser Timezone Offset Minutes":"INTEGER",
  "DBM Media Fee 5 (USD)":"INTEGER",
  "DBM CPM Fee 4 (USD)":"INTEGER",
  "Floodlight Configuration":"INTEGER",
  "DBM Media Cost (USD)":"INTEGER",
  "DBM CPM Fee 3 (Advertiser Currency)":"INTEGER",
  "billing_invoice_code":"STRING",
  "operating_system_id":"INTEGER",
  "creative_field_id":"INTEGER",
  "DBM ZIP/Postal Code":"STRING",
  "placement_id":"INTEGER",
  "placement_cap_cost_option":"INTEGER",
  "rich_media_event_type":"STRING",
  "DBM Exchange ID":"STRING",
  "Placement ID":"INTEGER",
  "floodlight_variable_id":"INTEGER",
  "city":"STRING",
  "placement_start_date":"INTEGER",
  "Interaction Time":"STRING",
  "site_directory_id":"INTEGER",
  "DBM CPM Fee 2 (Partner Currency)":"INTEGER",
  "DBM Data Fees (Partner Currency)":"INTEGER",
  "rendering_id":"INTEGER",
  "creative_image_url":"STRING",
  "DBM Browser/Platform ID":"INTEGER",
  "DBM Designated Market Area (DMA) ID":"INTEGER",
  "activity_sub_type":"STRING",
  "DBM Request Time":"INTEGER",
  "Activity ID":"INTEGER",
  "DBM Country ID":"STRING",
  "rich_media_event_type_id":"INTEGER",
  "DBM Insertion Order ID":"INTEGER",
  "Browser/Platform ID":"STRING",
  "Creative Version":"STRING",
  "activity_group":"INTEGER",
  "placement_rate":"INTEGER",
  "DBM Advertiser ID":"INTEGER",
  "activity":"STRING",
  "Browser/Platform Version":"STRING",
  "Total Revenue":"FLOAT",
  "placement_comments":"STRING",
  "DBM Billable Cost (Advertiser Currency)":"INTEGER",
  "Country Code":"STRING",
  "Segment Value 1":"INTEGER",
  "DBM Revenue (Partner Currency)":"INTEGER",
  "DBM Site ID":"INTEGER",
  "DBM CPM Fee 5 (Partner Currency)":"INTEGER",
  "DBM Media Fee 3 (Partner Currency)":"INTEGER",
  "DBM ISP ID":"INTEGER",
  "placement":"STRING",
  "ad_comments":"STRING",
  "Active View: Measurable Impressions":"INTEGER",
  "DBM City ID":"INTEGER",
  "keyword":"STRING",
  "creative_type":"STRING",
  "placement_strategy":"STRING",
  "Partner 3 ID":"STRING",
  "rich_media_event_id":"INTEGER",
  "DBM Device Type":"INTEGER",
  "landing_page_url":"STRING",
  "DBM Media Fee 3 (Advertiser Currency)":"INTEGER",
  "creative_rotation_type":"STRING",
  "DBM Revenue (Advertiser Currency)":"INTEGER",
  "DBM Media Fee 1 (Partner Currency)":"INTEGER",
  "DBM Data Fees (Advertiser Currency)":"INTEGER",
  "Active View: Eligible Impressions":"INTEGER",
  "DBM Media Cost (Partner Currency)":"INTEGER",
  "City":"STRING",
  "DBM CPM Fee 5 (USD)":"INTEGER",
  "DBM Media Fee 3 (USD)":"INTEGER",
  "ad":"STRING",
  "rich_media_event_name":"STRING",
  "DBM Media Fee 1 (USD)":"INTEGER",
  "site_id":"INTEGER",
  "site":"STRING",
  "DBM CPM Fee 2 (USD)":"INTEGER",
  "Site ID (DCM)":"INTEGER",
  "Activity Sub-Type":"INTEGER",
  "content_category":"STRING",
  "DBM Billable Cost (Partner Currency)":"INTEGER",
  "DBM Media Fee 5 (Partner Currency)":"INTEGER",
  "DBM CPM Fee 3 (Partner Currency)":"INTEGER",
  "site_keyname":"STRING",
  "Google Click ID":"STRING",
  "paid_search_keyword":"STRING",
  "DBM Auction ID":"STRING",
  "need description":"STRING",
  "Ad ID":"INTEGER",
  "DBM Media Fee 2 (Advertiser Currency)":"INTEGER",
  "Creative Pixel Size":"STRING",
  "DBM Data Fees (USD)":"INTEGER",
  "DBM Operating System ID":"INTEGER",
  "DBM Media Fee 4 (Advertiser Currency)":"INTEGER",
  "Total Conversions":"INTEGER",
  "Designated Market Area (DMA) ID":"INTEGER",
  "placement_total_booked_units":"INTEGER",
  "paid_search_ad_group":"STRING",
  "paid_search_ad_id":"INTEGER",
  "Referrer URL":"STRING",
  "Landing Page URL ID":"INTEGER",
  "DBM Media Fee 1 (Advertiser Currency)":"INTEGER",
  "dma_region":"STRING",
  "flighting_activated":"BOOLEAN",
  "campaign_start_date":"INTEGER",
  "creative_group2_id":"INTEGER",
  "DBM Media Fee 4 (Partner Currency)":"INTEGER",
  "Event Type":"STRING",
  "DBM CPM Fee 4 (Partner Currency)":"INTEGER",
  "browser_platform_id":"INTEGER",
  "DBM Media Cost (Advertiser Currency)":"INTEGER",
  "paid_search_landing_page_url":"STRING",
  "package_roadblock_type_id":"INTEGER",
  "DBM CPM Fee 1 (USD)":"INTEGER",
  "DBM Media Fee 4 (USD)":"INTEGER",
  "creative_group2":"STRING",
  "paid_search_campaign_id":"INTEGER",
  "tag_counting_method_id":"INTEGER",
  "creative_group1":"STRING",
  "paid_search_legacy_keyword_id":"INTEGER",
  "paid_search_campaign":"STRING",
  "DBM Mobile Make ID":"INTEGER",
  "activity_type":"STRING",
  "DBM Matching Targeted Segments":"STRING",
  "Conversion ID":"INTEGER",
  "creative_start_date":"INTEGER"
}
